PF1664 reference cloning instructions
DataBiosphere/terra-cli pull request #262
Opened 2022-06-01 00:41 UTC by ginaygoogle

2022-06-01 16:15 UTC, jaycarlton requested changes

2022-06-01 16:15 UTC, jaycarlton commented on src/main/java/bio/terra/cli/command/shared/options/ReferencedCloningInstructionsForUpdate.java
> +          "Instructions for handling when cloning the workspace: COPY_NOTHING, COPY_DEFINITION, COPY_RESOURCE.")
This should be `COPY_NOTHING, COPY_REFERENCE`.

2022-06-01 16:15 UTC, jaycarlton commented on src/main/java/bio/terra/cli/serialization/userfacing/input/UpdateReferencedBqTableParams.java
> +    private CloningInstructionsEnum cloningInstructions;
mark this `@Nullable` for documentation.

2022-06-01 16:15 UTC, jaycarlton commented on src/main/java/bio/terra/cli/serialization/userfacing/input/UpdateReferencedGcsObjectParams.java
> +    private CloningInstructionsEnum cloningInstructions;
`@Nullable`

2022-06-01 16:15 UTC, jaycarlton commented on src/main/java/bio/terra/cli/serialization/userfacing/input/UpdateReferencedGitRepoParams.java
>    public final UpdateResourceParams resourceFields;
I think all three of these should be `@Nullable`.

2022-06-01 16:15 UTC, jaycarlton commented on src/test/java/unit/BqDatasetReferenced.java
> +    assertEquals(newDescription, updatedDataset.description);
Looks like you have this line twice. Also, you're not asserting anything about the cloning instructions. I believe I fixed the bug that required doing a describe before checking it.

2022-06-01 16:15 UTC, jaycarlton commented on src/test/java/unit/BqTableReferenced.java
> +            "--description=" + newDescription,
This probably should be `--new-description`, but for another PR.

2022-06-01 16:15 UTC, jaycarlton commented on src/test/java/unit/GcsObjectReferenced.java
> +    assertEquals(CloningInstructionsEnum.REFERENCE, describedBucketObject.cloningInstructions);
I thought the new cloning option was `DEFINITION` not `REFERENCE`.

2022-06-01 16:15 UTC, jaycarlton commented on src/test/java/unit/GitRepoReferenced.java
> +    assertEquals(CloningInstructionsEnum.REFERENCE, describedGitRepo.cloningInstructions);
here again I thought the cloning should be `DEFINITION` based on the update command.

2022-06-01 19:56 UTC, melissachang reviewed
Please do some manual testing and paste the output here. This is a good thing to do in general. It tells the reviewers what you changed.

Please include missing args case: `terra resource update git-repo`

2022-06-01 19:56 UTC, melissachang commented on src/main/java/bio/terra/cli/command/resource/update/BqTable.java
>      description = "Update a BigQuery data table.",
nit put on line 27

2022-06-01 19:56 UTC, melissachang commented on src/test/java/unit/BqDatasetReferenced.java
>      // update just the description
// update description and cloning instructions

Please do this for all test files:

- Comment is accurate
- terra command in comment is accurate
- Assert cloning instruction was updated

2022-06-01 22:28 UTC, jaycarlton commented on src/main/java/bio/terra/cli/command/shared/options/ControlledCloningInstructionsForUpdate.java
> +      // Only COPY_NOTHING, COPY_DEFINITION and COPY_REFERENCE are allowed for referenced resources
It's only COPY_NOTHING and COPY_REFERENCE.

2022-06-06 21:44 UTC, melissachang approved these changes

2022-06-06 21:44 UTC, melissachang commented on src/main/java/bio/terra/cli/command/resource/update/BqTable.java
>      description = "Update a BigQuery data table.",
Sorry, I mean just move line 23 to line 27

2022-06-06 21:44 UTC, melissachang commented on src/main/java/bio/terra/cli/command/shared/options/CloningInstructionsForUpdate.java
>     * Use this --new-cloning flag when updating controlled resources.
Change `controlled resources` to `resources`.

2022-06-06 21:44 UTC, melissachang commented on src/main/java/bio/terra/cli/command/shared/options/CloningInstructionsForUpdate.java
> +      // two options or commands in the same class file with same name could not build
Makes sense. Replace 17-22 with:

```
      // For what is allowed, see:
      // https://github.com/DataBiosphere/terra-workspace-manager/blob/main/service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java#L448
      description =
          "Instructions for handling when cloning the workspace: COPY_NOTHING, COPY_DEFINITION, or COPY_RESOURCE for controlled resources; COPY_NOTHING or COPY_REFERENCE for referenced resources")
```

2022-06-06 21:44 UTC, melissachang commented on src/test/java/unit/BqDatasetReferenced.java
> +    // --new-cloning=COPY_NOTHING`
Here you have COPY_NOTHING, but on 341 you have NOTHING. For all tests, please make sure your comments are in sync

2022-06-06 21:44 UTC, melissachang commented on src/test/java/unit/BqDatasetReferenced.java
> +    assertEquals(description, describedDataset.description);
For description:

line 327: Assert old description
line 333: Update new description
line 349: Assert new description

You only have:

line 334: Update cloning instructinos
line 350: Assert new cloning instructions

You're missing:

line 328: assert old cloning instructions

For all we know, update could be broken and cloning instructions could have been set to NOTHING originally. line 328 makes us certain that updating works.

Please do this for all tests.

2022-06-07 21:11 UTC, jaycarlton approved these changes

2022-06-07 21:11 UTC, jaycarlton commented on src/test/java/unit/GitRepoReferenced.java
> +    describedGitRepo =
Same goes here: we shouldn't  need to describe to get the latest values.

2022-06-07 21:11 UTC, jaycarlton commented on src/main/java/bio/terra/cli/command/shared/options/CloningInstructionsForUpdate.java
> +          "Instructions for handling when cloning the workspace: COPY_NOTHING, COPY_DEFINITION, or COPY_RESOURCE for controlled resources; COPY_NOTHING or COPY_REFERENCE for referenced resources")
Put a period at the end of the description.

2022-06-09 15:39 UTC, merged