PF-763 Post startup script
DataBiosphere/terra-cli pull request #75
Opened 2021-05-13 20:00 UTC by wchamber

2021-05-17 18:56 UTC, wchamber commented on src/main/java/bio/terra/cli/command/resources/create/AiNotebook.java
> +          "https://raw.githubusercontent.com/DataBiosphere/terra-cli/wc-PF-763-post-startup-script/notebooks/post-startup.sh",
pointing at this branch for demoing, needs to be updated to point at main.

2021-05-18 15:14 UTC, marikomedlock commented on notebooks/post-startup.sh
> +sudo -u ${JUPYTER_USER} sh -c "curl -L https://github.com/DataBiosphere/terra-cli/releases/latest/download/download-install.sh | bash"
Just for curiosity, why does the CLI installation need to be done as the jupyter_user?

2021-05-18 15:14 UTC, marikomedlock commented on notebooks/post-startup.sh
> +sudo -u ${JUPYTER_USER} sh -c "./terra config set browser manual"
Is this startup script also the right place to call other config commands? e.g.:
- `terra workspace mount`
- `terra server set`
- `gcloud config set project`

2021-05-18 15:14 UTC, marikomedlock commented on notebooks/post-startup.sh
> +cd /tmp || exit
Should this line be moved up before the package installations, since the stdout/err file will not be generated if `/tmp` doesn't exist?

2021-05-18 15:27 UTC, deflaux commented
> Add an initial post startup script for AI Notebooks created by the CLI. This is an initial stub script that installs some python packages and the Terra CLI.

This looks like a good start for the setup relevant to all MC Terra users!

> The post startup script runs before the VM has any user credentials, so it can only do public actions.
> If there are any bash scripting best practices, please let me know.

I recommend @mbookman for the bash best practices review.

> In the future, we can set more metadata on the VM instance and pull it in the script from [GCE's metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata).

That's great! Configuring the git user name and email doesn't require any credentials, just the correct values to use.

> In the long term, we want to move the notebooks configuration out of CLI and to a dedicated Terra notebooks repo/service.

sound good!

2021-05-18 15:31 UTC, deflaux commented on notebooks/post-startup.sh
> +/opt/conda/bin/conda install -y pre-commit nbdime nbstripout pylint pytest
looking forward to seeing in a future PR how you would like to package up the setup needed for specific tutorial notebooks (e.g. there are a default set of tutorials we install, and the setup script for those tutorials first calls this setup script)

2021-05-18 16:49 UTC, mbookman requested changes

2021-05-18 16:49 UTC, mbookman commented on notebooks/post-startup.sh
> +JUPYTER_USER="jupyter"
If a variable is not expected to change, then recommend using "readonly":

```
readonly JUPYTER_USER="jupyter"
```

See https://google.github.io/styleguide/shellguide.html#quoting

2021-05-18 16:49 UTC, mbookman commented on notebooks/post-startup.sh
> +
Recommend 

```
set -o errexit
set -o nounset
set -o pipefail
```

As they help catch coding or execution errors closer to the point of failure.

2021-05-18 16:49 UTC, mbookman commented on notebooks/post-startup.sh
> +sudo -u ${JUPYTER_USER} sh -c "/opt/conda/bin/nbstripout --install --global"
Enclose variable expansion in double-quotes as a general practice.

https://google.github.io/styleguide/shellguide.html#quoting

2021-05-18 19:47 UTC, wchamber reviewed
Thanks!

2021-05-18 20:59 UTC, marikomedlock approved these changes

2021-05-18 21:21 UTC, deflaux commented on notebooks/post-startup.sh
> +/opt/conda/bin/conda install -y pre-commit nbdime nbstripout pylint pytest
we could make a read-only deploy key for the repo and store it in the metadata

2021-05-19 16:49 UTC, deflaux approved these changes

2021-05-20 13:58 UTC, merged